### ISSUE TITLE
Template code should use NT .flush() rather than .setUpdateRate()

### ISSUE THREAD

**Issue by kjaget** [wpilibsuite/frc-characterization#66]
Per the CD thread here - https://www.chiefdelphi.com/t/network-table-speed/368462, it looks like the preferred way to force NT to update more quickly is to use the .flush() method rather than setting the update rate.
The various template robot code snippets all seem to use setUpdateRate().
To line up with the method recommended in the linked thread, those calls should be removed and replaced with a .flush() call inside the generated autonomousPeriodic method.

**Comment by sciencewhiz** [comment]
That thread was addressing a specific use case where the user wanted data from a coprocessor as quickly as possible (minimum latency). Flush is the right option then because the data is sent immediately. In frc-characterization, the latency doesn't matter, as long as the data from each program loop is received. For that, setUpdateRate seems appropriate.
